apiVersion: v1
kind: Template
metadata:
  name: Nodejs-template
  annotations:
    openshift.io/display-name: Node.js
    description: A Node.js application with no database.
    tags: nodejs
    iconClass: icon-nodejs
    openshift.io/long-description: This template defines resources needed to develop a NodeJS application, including a build configuration and application deployment configuration.  It does not include a database.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
    template.openshift.io/bindable: "false"
message: "The following service(s) have been created in your project: ${PROJECT}."
labels:
  app: ${PROJECT}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      description: Keeps track of changes in the application image
    generation: 1
    labels:
      app: ${PROJECT}
    name: ${PROJECT}
parameters:
- description: "Project name"
  name: "PROJECT"
  value: ""
- description: "Branch name"
  name: "BRANCH_NAME"
  value: ""
- description: "Branch name hyphenated"
  name: "BRANCH_NAME_HY"
  value: ""
- description: "Branch name for container image hyphenated"
  name: "BRANCH_NAME_HY_CONTAINER_IMAGE"
  value: ""
- description: "Docker Registry"
  name: "DOCKER_REGISTRY"
  value: ""
- description: "Artifactory Token"
  name: "ARTIFACTORY_TOKEN"
  value: ""
- description: "WAR_FILE_URL"
  name: "WAR_FILE_URL"
  value: ""
- description: "SOURCE_REPOSITORY_URL"
  name: "SOURCE_REPOSITORY_URL"
  value: ""
- description: "SOURCE_REPOSITORY_BRANCH"
  name: "SOURCE_REPOSITORY_BRANCH"
  value: ""
- description: "NPM_MIRROR"
  name: "NPM_MIRROR"
  value: ""
- description: "NODEJS_VERSION"
  name: "NODEJS_VERSION"
  value: ""
- description: "EnvLabel"
  name: "envLabel"
  value: ""
- description: "Host Name"
  name: "HOST_NAME"
  value: ""
- description: "Minimum number of replicas of pods"
  name: "MIN_POD_REPLICAS"
  value: ""
- description: "Maximum number of replicas of pods"
  name: "MAX_POD_REPLICAS"
  value: ""